spring:
  datasource:
    username: bnkpay
    url: jdbc:mariadb://www.sjkim.net:3306/bnkpay
    driverClassName: org.mariadb.jdbc.Driver
    password: bnk1234
  security:
    user:
      name: admin
      password: password
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: create
server:
  port: '8000'
  
  
springdoc:
  version: '@springdoc.version@'
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  show-actuator: true
  packages-to-scan: com.bnk.pay.controller

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug